import type { Metadata } from "next";
import "./globals.css";
import Provider from "./provider";
import Navbar from "./navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="h-full dark antialiased"
    >
      <head>
        {/* Load heading font and preconnect external domains */}
        <link rel="preconnect" href="https://fonts.cdnfonts.com" />
        <link rel="stylesheet" href="https://fonts.cdnfonts.com/css/satoshi" />
      </head>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
